config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    resources :items, only: [:index, :show]
    get 'customers/my_page' => 'customers#show'
    get 'costomers/infomation/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all' => 'cart_items#destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm' => 'orders#confirm'
        get 'thanks' => 'orders#thanks'
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  with_options presence: do
    validates :payment_method
    validates :total_price
    validates :shipping_cost
    validates :post_code
    validates :address
    validates :name
    validates :status
  end

  enum payment_method: { credit_card: 0, transfer: 1}
  # 入金待ち0, 入金確認1, 製作中2, 発送準備中3, 発送済み4
  enum status: {wait_for_payment: 0, payment_confirmation: 1, in_making: 2, preparing_delivery: 3, delivered: 4}

  def post_code_and_address_and_name
    "〒#{self.post_code} #{self.address}\n#{self.name}"
  end

  def add_tax_price
    (self.price * 1.10).round
  end


  def total_price_sum
    self.total_price + self.shipping_cost
  end

  def total_item_amount #合計金額
   order_details.sum { |order_detail| order_detail.subtotal }
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
     @order = Order.find(params[:id])
    # @order_status = @order.statusｃ
    @order_details = OrderDetail.where(order_id: params[:id])
  end


  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)
    if @order.status == "payment_confirmation"
      @order_details.each do |order_detail|
        order_detail.update(making_status: 1)
      end
    end
    # if @order.update(order_params)
    #   @order_details.update_all(making_status: "制作待ち") if @order.status == "入金確認"
    # end
    redirect_to admin_order_path(@order.id), notice: "変更を完了しました"
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :post_code, :address, :name, :shipping_cost, :total_price, :payment_method, :status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
        <div class="w-25 bg-light text-center">
          <h4>注文履歴詳細</h4>
        </div>
        <div class="row my-2">

        <table class="table">
         <tbody>
           <tr>
            <td>購入者</td>
            <td><%= link_to @order.name, admin_customers_path %></td>
          </tr>

          <tr>
            <td>注文日</td>
            <td><%= @order.created_at %></td>
          </tr>

          <tr>
            <td>配送先</td>
            <td><%= @order.post_code_and_address_and_name %></td>
          </tr>

          <tr>
            <td>支払方法</td>
            <td><%= @order.payment_method_i18n %></td>
          </tr>

          <tr>
            <td>注文ステータス</td>
             <%= form_with model: @order, url: admin_order_path(@order) do |f| %>
            <td><%= f.select :status,Order.statuses_i18n.invert  %>
            <%= f.submit "更新",class: 'btn btn-success'%></td>
          </tr>
          <% end %>
         </tbody>
        </table>
      </div>
   </div>
</div>

  <div class="row my-4">
    <div class="col-8">
        <table class="table text-center mb-5">
          <thead class="bg-light">
            <tr>
              <th>商品名</th>
              <th>単価（税込）</th>
              <th>数量</th>
              <th>小計</th>
              <th>制作ステータス</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.item.with_tax_price %></td>
              <td><%= order_detail.quantity %></td>
              <td><%= order_detail.subtotal %></td>
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id)  do |f| %>
              <td> <%= f.select :making_status,  OrderDetail.making_statuses_i18n.invert %>
                   <%= f.submit "更新", class:"btn btn-success" %></td>
            </tr>
            <% end %>
            <% end %>
          </tbody>
        </table>
    </div>
    <div class="col-4">
      <table class="table">
        <thead>
        <tr>
          <td>商品合計</td>
          <td><%= @order.total_item_amount %></td>
        </tr>
        <tr>
          <td>送料</td>
          <td><%= @order.shipping_cost %></td>
        </tr>
        <tr>
          <td>請求金額合計</td>
          <td><%= @order.total_price %></td>
        </tr>
        </thead>
      </table>
    </div>
  </div>
</div>