config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    resources :items, only: [:index, :show]
    get 'customers/my_page' => 'customers#show'
    get 'costomers/infomation/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all' => 'cart_items#destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm' => 'orders#confirm'
        get 'thanks' => 'orders#thanks'
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  def post_code_and_address_and_name
    "〒#{self.post_code} #{self.address}\n#{self.name}"
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.with_tax_price * amount
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true


  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  belongs_to :genre
  has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def total_item_amount
    order_details.sum{ |order_detail| order_detail.subtotal }
  end

  validates :name, presence: true
  validates :item_description, presence: true
  validates :price, presence: true
  validates :image, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  with_options presence: do
    validates :payment_method
    validates :total_price
    validates :shipping_cost
    validates :post_code
    validates :address
    validates :name
    validates :status
  end

  enum payment_method: { credit_card: 0, transfer: 1}
  # 入金待ち0, 入金確認1, 製作中2, 発送準備中3, 発送済み4
  enum status: {wait_for_payment: 0, payment_confirmation: 1, in_making: 2, preparing_delivery: 3, delivered: 4}

  def post_code_and_address_and_name
    "〒#{self.post_code} #{self.address}\n#{self.name}"
  end

  def add_tax_price
    (self.price * 1.10).round
  end


  def total_price_sum
    self.total_price + self.shipping_cost
  end

  def total_item_amount #合計金額
   order_details.sum { |order_detail| order_detail.subtotal }
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order


  # 製作ステータス
  enum making_status: {impossible_manufacture:0, waiting_manufacture:1, manufacturing:2, finish:3}

  def subtotal # 小計
    self.price * self.quantity
  end

  private

  def params_order_detail
    params.require(:order_detail).permit(:order_id, :item_id, :price, :quantity, :making_status)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genres = Genre.all
    @genre = Genre.new
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "ジャンルを追加しました"
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "変更しました"
    else
      render :edit
    end
  end
  
  
  private
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    # ジャンル作ったので@item.genre_id = 1消した
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :item_description, :price, :is_active, :image )
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
     @order = Order.find(params[:id])
    # @order_status = @order.statusｃ
    @order_details = OrderDetail.where(order_id: params[:id])
  end


  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)
    if @order.status == "payment_confirmation"
      @order_details.each do |order_detail|
        order_detail.update(making_status: 1)
      end
    end
    # if @order.update(order_params)
    #   @order_details.update_all(making_status: "制作待ち") if @order.status == "入金確認"
    # end
    redirect_to admin_order_path(@order.id), notice: "変更を完了しました"
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :post_code, :address, :name, :shipping_cost, :total_price, :payment_method, :status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamE_Naganocake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/0e739b83f5.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="border border-dark pt-4 pb-4">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <h4>
            <%= link_to "Nagano Cake", root_path, class:"font-weight-bold font-italic" %>
          </h4>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
              <li class="nav-item">
                <p> ようこそ、<%= current_customer.last_name %>さん!</p>
              </li>
              <li class="nav-item">
                <%= link_to "マイページ", customers_my_page_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "カート", cart_items_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
              </li>
              <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "注文履歴一覧", admin_root_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to "About", about_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer>
      <div class="border-top border-dark pt-5 pb-4"></div>
    </footer>
  </body>
</html>